spring:
  application:
    name: loganalyzer
  datasource:
    url: jdbc:h2:file:./data/logs;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true