name: CI

on:
  pull_request:
  push:
    branches: [ "**" ]

jobs:
  build-and-test:
    name: Build & Test (Maven, JDK 21)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build & test
        run: mvn -B -ntp clean verify
  docker-publish:
    name: Build & Push Docker image to GHCR
    runs-on: ubuntu-latest
    needs: build-and-test
    # GITHUB_TOKEN can push to GHCR with these permissions:
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/loganalyzer
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/loganalyzer:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/loganalyzer:buildcache,mode=max
